[project]
name = "custom-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "imrat", email = "imtiaj.hossain@bjit.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.0.5",
    "node>=2.0.0",
    "npx>=0.1.8",
]

[project.scripts]
custom-mcp-server = "custom_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
