[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "imrat-67", email = "imtiajhossain7862@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=1.6.4",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-ollama>=1.1.0",
    "streamlit>=1.64.0",
]

[project.scripts]
mcp-client = "mcp_client:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
